### ISSUE TITLE
Windows body is selectionable

### ISSUE THREAD

**Issue by ariedro** [JuanGaray93/juangaray#1]
The `<p>` tag inside the Window body is selectionable, as one would expect in html, but it shouldn't if you're trying to emulate the windows's window funcionality

![image](https://user-images.githubusercontent.com/25304241/82008843-23282f00-9644-11ea-8414-29de3f1ceedb.png)

**Comment by JuanGaray93** [comment]
This is by design. The `p` tag is a plaecholder and elements inside a window are usually selectable. This is the case with the contents of a browser or of a text editor, for instance.

Expect a future release with examples of selectable and non-selectable content.
